apiVersion: v1
kind: Secret
metadata:
  name: csappstore-secret
data:
  APPSTORE_DJANGO_USERNAME: ""
  APPSTORE_DJANGO_PASSWORD: ""
  SECRET_KEY: ""
  OAUTH_PROVIDERS: ""
  GITHUB_NAME: ""
  GITHUB_KEY: ""
  GITHUB_SITES: ""
  GITHUB_CLIENT_ID: ""
  GITHUB_SECRET: ""
  GOOGLE_NAME: ""
  GOOGLE_KEY: ""
  GOOGLE_SITES: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_SECRET: ""
