kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "tycho-api.name" . }}-access
rules:
- apiGroups:
  - "*"
  # added pvc resource
  resources:
  - pods
  - services
  - services/status
  - persistentvolumeclaims
  - persistentvolumes
  - deployments/rollback
  - deployments/scale
  - ingresses
  - replicasets
  - replicasets/scale
  - clusterrole
  - clusterrolebinding
  - networkpolicies
  - deployments
  - replicasets
  - ingresses
  - namespaces
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "tycho-api.name" . }}-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "tycho-api.name" . }}-access
  apiGroup: rbac.authorization.k8s.io
