apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-{{ template "appstore.name" . }}
  labels:
    app: cs-{{ template "appstore.name" . }}
spec:
  selector:
    matchLabels:
      app: cs-{{ template "appstore.name" . }}
  template:
    metadata:
      labels:
        app: cs-{{ template "appstore.name" . }}
    spec:
      initContainers:
      - name: {{ .Values.db.name }}-init
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup {{ .Values.db.name }}; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: cs-{{ .Values.db.name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        command: ['/bin/bash', '-c']
        args: ["bin/appstore updatedb {{ .Values.djangoSettings }} && bin/appstore createsuperuser && bin/appstore run {{ .Values.djangoSettings }}"]
        # For debugging when things go wrong.
        # args: ["-c", "while true; do date; sleep 5; done"]
        env:
        - name: OAUTH_SERVICE_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: OAUTH_SERVICE_SERVER_URL
              name: csappstore-env
        - name: OAUTH_APP_KEY
          valueFrom:
            configMapKeyRef:
              key: OAUTH_APP_KEY
              name: csappstore-env
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              key: DATABASE_USER
              name: csappstore-env
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PASSWORD
              name: csappstore-env
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: csappstore-env
        - name: OAUTH_DB_DIR
          valueFrom:
            configMapKeyRef:
              key: OAUTH_DB_DIR
              name: csappstore-env
        - name: OAUTH_DB_FILE
          valueFrom:
            configMapKeyRef:
              key: OAUTH_DB_FILE
              name: csappstore-env
        - name: CSAPPSTORE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY
              name: csappstore-secret
        - name: APPSTORE_DJANGO_USERNAME
          valueFrom:
            secretKeyRef:
              key: APPSTORE_DJANGO_USERNAME
              name: csappstore-secret
        - name: APPSTORE_DJANGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: APPSTORE_DJANGO_PASSWORD
              name: csappstore-secret
        - name: OAUTH_PROVIDERS
          valueFrom:
            secretKeyRef:
              key: OAUTH_PROVIDERS
              name: csappstore-secret
        - name: GITHUB_NAME
          valueFrom:
            secretKeyRef:
              key: GITHUB_NAME
              name: csappstore-secret
        - name: GITHUB_SITES
          valueFrom:
            secretKeyRef:
              key: GITHUB_SITES
              name: csappstore-secret
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: GITHUB_CLIENT_ID
              name: csappstore-secret
        - name: GITHUB_SECRET
          valueFrom:
            secretKeyRef:
              key: GITHUB_SECRET
              name: csappstore-secret
        - name: GOOGLE_NAME
          valueFrom:
            secretKeyRef:
              key: GOOGLE_NAME
              name: csappstore-secret
        - name: GOOGLE_SITES
          valueFrom:
            secretKeyRef:
              key: GOOGLE_SITES
              name: csappstore-secret
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: GOOGLE_CLIENT_ID
              name: csappstore-secret
        - name: GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              key: GOOGLE_SECRET
              name: csappstore-secret
        ports:
        - containerPort: 8000
      {{- if .Values.oauth.pvcname }}
        volumeMounts:
          - mountPath: /var/lib/sqlite3
            name: appstore-oauth-volume
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      restartPolicy: Always
      {{- if .Values.oauth.pvcname }}
      volumes:
        - name: appstore-oauth-volume
          persistentVolumeClaim:
            claimName: {{ .Values.oauth.pvcname }}
      {{- end }}
