kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.db.name }}-pv-volume
  labels:
    type: local
    app: {{ .Values.db.name }}
spec:
  storageClassName: {{ .Values.db.name }}
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: appstore-db-volume
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.db.name }}-pv-claim
  labels:
    app: {{ .Values.db.name }}
spec:
  storageClassName: {{ .Values.db.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
